In [5]:
import torch
from torch import nn

In [2]:
x = [[1,2],[3,4],[5,6],[7,8]]
y = [[3],[7],[11],[15]]


In [3]:
X = torch.tensor(x).float()
Y = torch.tensor(y).float()

In [4]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
X = X.to(device)
Y = Y.to(device)

cuda


In [7]:
class MyNeuralNet(nn.Module):
        def __init__(self):
                super().__init__()
                self.input_to_hidden_layer = nn.Linear(2, 8)
                self.hidden_layer_activation = nn.ReLU()
                self.hidden_layer_to_ouput_layer = nn.Linear(8, 1)

In [8]:
my_net = MyNeuralNet().to(device)

In [12]:
for par in my_net.parameters():
 print(par)


Parameter containing:
tensor([[ 0.6977, -0.5288],
        [-0.1620, -0.5441],
        [-0.1025, -0.4352],
        [-0.0763,  0.0160],
        [ 0.1219,  0.2867],
        [-0.2247,  0.5232],
        [-0.3837,  0.6413],
        [-0.5822,  0.4449]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.5420, -0.4484, -0.2835, -0.5683, -0.1660, -0.0465, -0.2131,  0.4055],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([[ 0.0653,  0.1530, -0.0022, -0.0078, -0.3198, -0.2726,  0.1789, -0.1304]],
       device='cuda:0', requires_grad=True)
Parameter containing:
tensor([-0.2567], device='cuda:0', requires_grad=True)


In [6]:
print(nn.Linear(2, 7))


Linear(in_features=2, out_features=7, bias=True)


In [ ]:
loss_func = nn.MSELoss()