In [1]:
import torch

In [5]:
x = torch.tensor([1, 2, 3, 4], dtype=torch.float64)
y = torch.tensor([5, 6, 7, 8])
x, y

(tensor([1., 2., 3., 4.], dtype=torch.float64), tensor([5, 6, 7, 8]))

In [4]:
a = torch.Size([1, 2])
a

torch.Size([1, 2])

In [6]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
torch.ones((4, 5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])